# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: team1-accounts-deployment
containerName: team1-accounts-container
serviceName: team1-accounts-service
appLabel: team1-accounts-app

replicaCount: 1

image:
  repository: group1-team1-accounts-service

service:
  nodePort: 30141


eazybankcommon:
  service:
    targetPort: 9206
  containerPort: 9206
  image:
    tag: latest
